#index:
#    path: /
#    controller: App\Controller\DefaultController::index


app_homepage:
  path: /
  defaults:
    _controller: 'App\Controller\HomeController::index'


    app_register:
      path: /
      defaults:
        _controller: 'App\Controller\RegisterController::show'