#index:
#    path: /
#    controller: App\Controller\DefaultController::index


app_homepage:
  path: /
  defaults:
    _controller: 'App\Controller\HomeController::index'


    app_register:
      path: /
      defaults:
        _controller: 'App\Controller\RegisterController::show'

        app_login:
          path: /
          defaults:
            _controller: 'App\Controller\LoginController::index'

            app_logout:
              path: /logout
              methods: GET


              app_todo:
                path: /
                defaults:
                  _controller: 'App\Controller\TodoController::index'

                  names_details:
                    path: /{name}
                    defaults:
                      _controller: 'App\Controller\TodoController::todoDetails'






